name: 버그 제보
description: 발견한 버그를 제보합니다.
labels: [버그]
title: "[Bug]: "
body:
  - type: textarea
    id: description
    attributes:
      description: 버그에 대해서 설명해주세요.
      label: 현상
    validations:
      required: true
      resize: none

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 버그가 발생하는 환경
      description: 어떤 상황에서 생기는 버그인 지 알려주세요. 특정 환경에서만 발생하는 것 같다면, OS와 환경에 대한 정보도 함께 제공해주세요.
      placeholder: 최소한으로 재현 가능한 코드 또는 재현 단계를 설명해주세요. 선택 사항이지만 권장됩니다.

  - type: textarea
    id: possible-solution
    attributes:
      label: 예상되는 해결책
      description: 예상되는 해결책이 있다면 공유해주세요.
    validations:
      required: false

  - type: textarea
    id: etc
    attributes:
      label: 기타
    validations:
      required: false
